data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
paths:
  html:
    main: "data/raw/dataMister.html"
    aux: "data/raw/dashboard.html"
    clas_main: "data/raw/ClassificationMister.html"
    clas_aux: "data/raw/clasificacion.html"
    mercado: "data/raw/mercado.html"
    jornadas: "data/raw/mi_equipo.html"
    subidas_bajadas: "data/raw/MarketSubidasBajadas.html"
    gameweek: "data/raw/gameweek.html"
    quiniela: "data/raw/quiniela.html"

  csv:
    notificaciones: "data/processed/ganancias.csv"
    clasificaciones: "data/processed/clasificaciones.csv"
    mercado: "data/processed/mercado.csv"
    jornada: "data/processed/jornadas.csv"
    subidas_bajadas: "data/processed/subidasBajadas.csv"
    notificaciones_clean: "data/processed/ganancias_clean.csv"
    notificaciones_jugador: "data/processed/ganancias_jugador.csv"
    clausulas_acuerdos: "data/processed/clausulas_acuerdos.csv"
    model: "data/processed/data_model.csv"
    gameweek: "data/processed/gameweek.csv"
    quiniela: "data/processed/quiniela.csv"

    test: "data/processed/test.csv"
  json:
    news: "newspaper/json/"
    
  pdf:
    template: "dashboards/templates/monthly_template.pdf"
    reports: "dashboards/reports/"
  images:
    teams_dir: "assets/"
    default_team: "default.png"
    news_utils: "newspaper/photos/"
    news: "newspaper/new/"
  results:
    data_audit: "results/auditoria_dataset.csv"

scraper:
  delay: 2
  scroll_pause: 2
  max_scrolls: 60
  headless: true

logging:
  level: "INFO"
  file: "logs/app.log"
